--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BEER
--------------------------------------------------------

  CREATE TABLE "BEER" 
   (	"PRODUCT_NAME" VARCHAR2(30 BYTE), 
	"CAPACITY_ML" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"SALES" NUMBER, 
	"QUANTITY" NUMBER, 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIQUOR
--------------------------------------------------------

  CREATE TABLE "LIQUOR" 
   (	"PRODUCT_NAME" VARCHAR2(30 BYTE), 
	"CAPACITY_ML" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"SALES" NUMBER, 
	"QUANTITY" NUMBER, 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RICEWINE
--------------------------------------------------------

  CREATE TABLE "RICEWINE" 
   (	"PRODUCT_NAME" VARCHAR2(30 BYTE), 
	"CAPACITY_ML" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"SALES" NUMBER, 
	"QUANTITY" NUMBER, 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOJU
--------------------------------------------------------

  CREATE TABLE "SOJU" 
   (	"PRODUCT_NAME" VARCHAR2(20 BYTE), 
	"CAPACITY_ML" NUMBER, 
	"UNIT_PRICE" NUMBER, 
	"SALES" NUMBER, 
	"QUANTITY" NUMBER, 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into BEER
SET DEFINE OFF;
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('오비맥주',350,2000,5000,550,to_date('20/03/22','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('코젤다크시나몬',350,3000,7500,80,to_date('20/01/24','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('생맥주',500,2500,4500,50,to_date('20/02/27','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('아사히',375,1700,3000,1100,to_date('20/03/17','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('카스',350,1000,3000,70,to_date('20/02/29','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('코젤다크',450,2700,6500,50,to_date('20/01/17','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('KGB',375,500,3500,60,to_date('20/02/21','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('크루저',350,1200,3000,70,to_date('20/02/03','RR/MM/DD'));
Insert into BEER (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('머드쉐이크',350,1500,3000,99,to_date('20/03/23','RR/MM/DD'));
REM INSERTING into LIQUOR
SET DEFINE OFF;
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('쿠엘포모히토',700,8000,24990,20,to_date('20/02/13','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('예거마이스터',1000,11500,36490,15,to_date('20/01/30','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('봄베이사파이어진',1000,9850,37490,13,to_date('19/12/03','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('앱솔루트보드카',1000,11100,30990,17,to_date('18/10/22','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('조니워커블루레이블',750,75230,228790,8,to_date('17/09/29','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('글렌피딕',700,48120,93900,13,to_date('18/02/15','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('시바스리갈18년산',700,38500,119900,3,to_date('19/07/03','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('호세쿠엘보데킬라',1000,9520,38990,23,to_date('20/03/10','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('말리부캐리비안럼',750,7750,21490,30,to_date('20/02/15','RR/MM/DD'));
Insert into LIQUOR (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('아구아',700,9200,42000,27,to_date('19/10/06','RR/MM/DD'));
REM INSERTING into RICEWINE
SET DEFINE OFF;
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('장수막걸리',750,1200,111,111,to_date('20/01/13','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('국순당',750,1500,3500,120,to_date('20/03/02','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('가평막걸리',1000,1000,3000,80,to_date('20/02/24','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('해창막걸리',900,900,3200,135,to_date('20/01/27','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('지평막걸리',1200,1500,4500,220,to_date('20/03/16','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('복순도가손막걸리',935,12000,36000,30,to_date('20/03/09','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('금정산성막걸리',750,800,3100,100,to_date('20/02/17','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('배상면주가',1000,1200,3800,180,to_date('20/01/21','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('우도땅콩막걸리',750,800,3800,250,to_date('20/01/03','RR/MM/DD'));
Insert into RICEWINE (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('호랑이생막걸리',750,700,3100,300,to_date('19/12/23','RR/MM/DD'));
REM INSERTING into SOJU
SET DEFINE OFF;
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('참이슬',360,1015,1350,200,to_date('20/01/15','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('처음처럼',360,1007,1350,200,to_date('20/01/15','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('좋은데이',360,1005,1350,300,to_date('20/02/03','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('진로이즈백',360,1030,1500,400,to_date('20/03/01','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('한라산',360,1050,1600,150,to_date('20/03/02','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('잎새주',360,1010,1350,100,to_date('20/03/03','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('C1',360,1008,1350,250,to_date('20/03/04','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('참이슬팩',200,750,1050,100,to_date('20/03/07','RR/MM/DD'));
Insert into SOJU (PRODUCT_NAME,CAPACITY_ML,UNIT_PRICE,SALES,QUANTITY,ORDER_DATE) values ('참이슬포켓',200,750,1050,100,to_date('20/03/10','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index BEER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BEER_PK" ON "BEER" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LIQUOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LIQUOR_PK" ON "LIQUOR" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RICEWINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RICEWINE_PK" ON "RICEWINE" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOJU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOJU_PK" ON "SOJU" ("PRODUCT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BEER
--------------------------------------------------------

  ALTER TABLE "BEER" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BEER" ADD CONSTRAINT "BEER_PK" PRIMARY KEY ("PRODUCT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LIQUOR
--------------------------------------------------------

  ALTER TABLE "LIQUOR" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "LIQUOR" ADD CONSTRAINT "LIQUOR_PK" PRIMARY KEY ("PRODUCT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RICEWINE
--------------------------------------------------------

  ALTER TABLE "RICEWINE" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "RICEWINE" ADD CONSTRAINT "RICEWINE_PK" PRIMARY KEY ("PRODUCT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOJU
--------------------------------------------------------

  ALTER TABLE "SOJU" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SOJU" ADD CONSTRAINT "SOJU_PK" PRIMARY KEY ("PRODUCT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
